name: Wakatime Stats Update

on:
  schedule:
    - cron: '0 * * * *' # This runs the job every hour
  push:
    branches:
      - main # Use your default branch name

jobs:
  update-readme:
    runs-on: ubuntu-latest # This specifies the runner provided by GitHub Actions
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Wakatime Readme Stats
        uses: miermontoto/waka-readme-stats@v5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Display options
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE_PER_REPO: true
